### ISSUE TITLE
install axios & create instance for it 

### ISSUE THREAD

**Issue by KrystianOg** [SzymCode/ContactBook#22]
https://axios-http.com/docs/instance

**Comment by KrystianOg** [comment]
You can also try to wrap your own hook around it to make your life easier

**Comment by SzymCode** [comment]
Here you are!

**Comment by KrystianOg** [comment]
I wouldn't say it's done, also if someone assigns you an issue let them close it

**Comment by SzymCode** [comment]
> I wouldn't say it's done, also if someone assigns you an issue let them close it

Check it now :)
